version: '3.8'

services:
  osd-server:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: osd-server
    ports:
      - "8280:8280"
    volumes:
      - ./store:/app/store
      - .:/app
    restart: unless-stopped
    networks:
      - storage-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./store:/app/store:ro
    depends_on:
      - go-server
    restart: unless-stopped
    networks:
      - storage-network

networks:
  storage-network:
    driver: bridge

volumes:
  store: